name: stephen
favicon: null
layout_spectrum: 0.6822919459082186
typography_spectrum: 0.4620308098383248
title: 'Stephen McElhinney | Blog'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6976758195087314
  lightness: 0.5130123989656568
  saturation: 0.25245221820659935
  rhythmicContrast: 0.004862257745116949
purpose: []
